app/views/led.py
import datetime
import json

from flask import Blueprint, Response, abort, current_app as app, redirect, render_template, request, url_for
from flask_babel import gettext
from sqlalchemy import func, select

from app.models.db import get_db, t_led, t_report_definition
from app.models.utils import create_led_report_template, get_menu_items, json_default

led_bp = Blueprint('led', __name__, url_prefix='/led')


@led_bp.route('/data/')
def data():
    """Returns available leds from the database. Can be optionally filtered by year.

    This is called from templates/led/index.html when the year input is changed.
    """
    startTime = request.args.get('startTime')
    endTime = request.args.get('endTime')
    year = request.args.get('year')
    if year:
        try:
            year = int(year)
        except (ValueError, TypeError):
            abort(400, 'invalid year parameter')
    else:
        year = None
    return json.dumps(get_leds(year), default=json_default)


@led_bp.route('/edit/')
@led_bp.route('/edit/<int:led_id>')
def edit(led_id=None):
    """Shows an edit form to add new or edit an existing led."""
    db_engine = get_db()
    rv = dict()
    rv['menu_items'] = get_menu_items('led')
    if led_id:
        with db_engine.begin() as connection:
            led = connection.execute(
                select(t_led)
                .where(t_led.c.id == led_id)
            ).fetchone()
        if not led:
            redirect(url_for('led.index'))
        rv['is_new'] = False
        rv['led'] = json.dumps(dict(
            id=led.id, state=led.state, date=led.date
        ))
    else:
        rv['is_new'] = True
        rv['led'] = json.dumps(dict(id='', state='', date=''))
    return render_template('led/edit.html', **rv)


@led_bp.route('/')
@led_bp.route('/index')
def index():
    """Shows a page where all available leds are listed."""
    rv = dict()
    rv['menu_items'] = get_menu_items('led')
    rv['leds'] = json.dumps(get_leds(), default=json_default)
    print(rv)
    return render_template('led/index.html', **rv)


@led_bp.route('/report/')
def report():
    """Prints a pdf file with all available leds.

    The leds can be optionally filtered by year. reportbro-lib is used to
    generate the pdf file. The data itself is retrieved
    from the database (*get_leds*). The report_definition
    is also stored in the database and is created on-the-fly if not present (to make
    this Demo App easier to use).
    """
    from reportbro import Report, ReportBroError

    print('request',request.args)
    year = request.args.get('year')
    if year:
        try:
            year = int(year)
        except (ValueError, TypeError):
            abort(400, 'invalid year parameter')
    else:
        year = None

    db_engine = get_db()

    # NOTE: these params must match exactly with the parameters defined in the
    # report definition in ReportBro Designer, check the name and type (Number, Date, List, ...)
    # of those parameters in the Designer.
    params = dict(year=year, leds=get_leds(year), current_date=datetime.datetime.now())

    with db_engine.begin() as connection:
        report_count = connection.execute(
            select(func.count(t_report_definition.c.id))
            .where(t_report_definition.c.report_type == 'leds_report')
        ).scalar()
        if report_count == 0:
            create_led_report_template()

        report_definition = connection.execute(
            select(t_report_definition.c.id, t_report_definition.c.report_definition)
            .where(t_report_definition.c.report_type == 'leds_report')
        ).fetchone()
        if not report_definition:
            raise abort(500, 'no report_definition available')

    try:
        report_inst = Report(report_definition.report_definition, params)
        if report_inst.errors:
            # report definition should never contain any errors,
            # unless you saved an invalid report and didn't test in ReportBro Designer
            raise ReportBroError(report_inst.errors[0])

        pdf_report = report_inst.generate_pdf()
        response = Response()
        response.headers['Content-Type'] = 'application/pdf'
        response.headers['Content-Disposition'] = 'inline; filename="leds.pdf"'
        response.set_data(bytes(pdf_report))
        return response
    except ReportBroError as ex:
        app.logger.error(ex.error)
        abort(500, 'report error: ' + str(ex.error))
    except Exception as ex:
        abort(500, 'report exception: ' + str(ex))


@led_bp.route('/save',  methods=['POST'])
def save():
    """Saves a music led in the db."""
    db_engine = get_db()
    json_data = request.get_json(silent=True)
    print(json_data)
    if json_data is None:
        abort(400, 'invalid request values')
    led = json_data.get('led')
    if not isinstance(led, dict):
        abort(400, 'invalid values')
    led_id = None
    if led.get('id'):
        try:
            led_id = int(led.get('id'))
        except (ValueError, TypeError):
            abort(400, 'invalid led id')

    values = dict()
    rv = dict(errors=[])

    # perform some basic form validation
    if not led.get('state'):
        rv['errors'].append(dict(field='state', msg=str(gettext('error.the field must not be empty'))))
    else:
        values['state'] = led.get('state') 
        values['date'] = datetime.datetime.now()

    #print(json_data)
    #print(led)
    #print(values)
    #print(rv)

    if not rv['errors']:
        # no validation errors -> save led
        with db_engine.begin() as connection:
            if led_id:
                connection.execute(
                    t_led.update()
                    .where(t_led.c.id == led_id)
                    .values(**values)
                )
            else:
                connection.execute(
                    t_led.insert()
                    .values(**values)
                )
    return json.dumps(rv)


def get_leds(startTime=None, endTime=None):
    """Returns available leds from the database. Can be optionally filtered by year."""
    db_engine = get_db()
    select_leds = select(t_led)
    items = []

    if startTime is not None:
        select_leds = select_leds.where(t_led.c.date >= startTime)
    if endTime is not None:
        select_leds = select_leds.where(t_led.c.date <= endTime)

    with db_engine.begin() as connection:
        rows = connection.execute(select_leds).fetchall()
        for row in rows:
            items.append(dict(
                id=row.id, state=row.state, date=row.date
            ))
    return items

app/views/report.py
import datetime
import decimal
import json
import uuid

from flask import abort, Blueprint, render_template, Response, request
from reportbro import Report, ReportBroError
from sqlalchemy import func, select
from timeit import default_timer as timer

from app.models.db import get_db, t_report_definition, t_report_request, t_led
from app.models.utils import create_led_report_template, get_menu_items, get_leds


report_bp = Blueprint('report', __name__, url_prefix='/report')

MAX_CACHE_SIZE = 1000 * 1024 * 1024  # keep max. 1000 MB of generated pdf files in sqlite db


@report_bp.route('/edit')
def edit():
    create_led_report_template()
    """Shows a page with ReportBro Designer to edit our albums report template.

    The report template is loaded from the db (report_definition table),
    in case no report template exists a hardcoded template is generated in
    *create_led_report_template* for this Demo App. Normally you'd probably
    start with an empty report (empty string, so no report is loaded
    in the Designer) in this case.
    """
    db_engine = get_db()
    rv = dict()
    rv['menu_items'] = get_menu_items('report')

    with db_engine.begin() as connection:
        report_count = connection.execute(
            select(func.count(t_report_definition.c.id))
            .where(t_report_definition.c.report_type == 'led_report')
        ).scalar()
        if report_count == 0:
            create_led_report_template()

        # load ReportBro report definition stored in our report_definition table
        row = connection.execute(
            select(t_report_definition.c.id, t_report_definition.c.report_definition)
            .where(t_report_definition.c.report_type == 'led_report')
        ).fetchone()
    print(row)
    print(rv)
    rv['report_definition'] = json.dumps(row.report_definition)
    return render_template('report/edit.html', **rv)


@report_bp.route('/run', methods=['GET', 'PUT', 'OPTIONS'])
def run():
    """Generates a report for preview.

    This method is called by ReportBro Designer when the Preview button is clicked,
    the url is defined when initializing the Designer, see *reportServerUrl*
    in templates/report/edit.html
    """
    response = Response()
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'GET, PUT, OPTIONS'
    response.headers['Access-Control-Allow-Headers'] =\
        'Origin, X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept, Authorization, Z-Key'
    if request.method == 'OPTIONS':
        # options request is usually sent by browser for a cross-site request, we only need to set the
        # Access-Control-Allow headers in the response so the browser sends the following get/put request
        return response

    additional_fonts = []
    # add additional fonts here if additional fonts are used in ReportBro Designer

    db_engine = get_db()
    with db_engine.begin() as connection:
        if request.method == 'PUT':
            # all data needed for report preview is sent in the initial PUT request, it contains
            # the format (pdf or xlsx), the report itself (report_definition), the data (test data
            # defined within parameters in the Designer) and is_test_data flag (always True
            # when request is sent from Designer)
            
            json_data = request.get_json(silent=False)
            #print('json_data', json_data)
            if json_data is None:
                abort(400, 'invalid request')
            output_format = json_data.get('outputFormat')
            if output_format not in ('pdf', 'xlsx'):
                abort(400, 'outputFormat parameter missing or invalid')
            report_definition = json_data.get('report')
            data = json_data.get('data')
            print('report data', data)
            row = get_leds()
            print(row)
            data['albums'] = row
            is_test_data = False
            report = None
            try:
                report = Report(report_definition, data, is_test_data, additional_fonts=additional_fonts)
            except Exception as e:
                abort(400, 'failed to initialize report: ' + str(e))

            if report.errors:
                # return list of errors in case report contains errors, e.g. duplicate parameters.
                # with this information ReportBro Designer can select object containing errors,
                # highlight erroneous fields and display error messages
                response.set_data(json.dumps(dict(errors=report.errors), default=jsonconverter))
                return response
            try:
                now = datetime.datetime.now()

                # delete old reports (older than 3 minutes) to avoid table getting too big
                connection.execute(
                    t_report_request.delete()
                    .where(t_report_request.c.created_on < (now - datetime.timedelta(minutes=3)))
                )

                total_size = connection.execute(
                    select(func.sum(t_report_request.c.pdf_file_size))
                ).scalar()
                if total_size and total_size > MAX_CACHE_SIZE:
                    # delete all reports older than 10 seconds to reduce db size for cached pdf files
                    connection.execute(
                        t_report_request.delete()
                        .where(t_report_request.c.created_on < (now - datetime.timedelta(seconds=10)))
                    )

                start = timer()
                report_file = report.generate_pdf(add_watermark=True)
                end = timer()
                print('pdf generated in %.3f seconds' % (end-start))

                key = str(uuid.uuid4())
                # add report request into sqlite db, this enables downloading the report by url
                # (the report is identified by the key) without any post parameters.
                # This is needed for pdf and xlsx preview.
                connection.execute(
                    t_report_request.insert()
                    .values(
                        key=key, report_definition=json.dumps(report_definition),
                        data=json.dumps(data, default=jsonconverter), is_test_data=is_test_data,
                        pdf_file=report_file, pdf_file_size=len(report_file), created_on=now
                    )
                )
                response.set_data('key:' + key)
                return response
            except ReportBroError as err:
                # in case an error occurs during report generation a ReportBroError exception is thrown
                # to stop processing. We return this error within a list so the error can be
                # processed by ReportBro Designer.
                response.set_data(json.dumps(dict(errors=[err.error]), default=jsonconverter))
                return response

        elif request.method == 'GET':
            output_format = request.args.get('outputFormat')
            assert output_format in ('pdf', 'xlsx')
            key = request.args.get('key')
            print('key',key)
            report = None
            report_file = None
            if key and len(key) == 36:
                # the report is identified by a key which was saved
                # in an sqlite table during report preview with a PUT request
                row = connection.execute(
                    select(t_report_request)
                    .where(t_report_request.c.key == key)
                ).fetchone()
                if not row:
                    abort(400, 'report not found (preview probably too old), update report preview and try again')
                if output_format == 'pdf' and row.pdf_file:
                    report_file = row.pdf_file
                else:
                    report_definition = json.loads(row.report_definition)
                    data = json.loads(row.data)
                    is_test_data = row.is_test_data
                    report = Report(report_definition, data, is_test_data, additional_fonts=additional_fonts)
                    if report.errors:
                        abort(400, 'error generating report')
            else:
                # in case there is a GET request without a key we expect all report data to be available.
                # this is NOT used by ReportBro Designer and only added for the sake of completeness.
                json_data = request.get_json(silent=True)
                if json_data is None:
                    abort(400, 'invalid request')
                report_definition = json_data.get('report')
                data = json_data.get('data')
                is_test_data = bool(json_data.get('isTestData'))
                if not isinstance(report_definition, dict) or not isinstance(data, dict):
                    abort(400, 'report_definition or data missing')
                report = Report(report_definition, data, is_test_data, additional_fonts=additional_fonts)
                if report.errors:
                    abort(400, 'error generating report')

            try:
                # once we have the reportbro.Report instance we can generate
                # the report (pdf or xlsx) and return it
                now = datetime.datetime.now()
                if output_format == 'pdf':
                    if report_file is None:
                        # as it is currently implemented the pdf file is always stored in the
                        # report_request table along the other report data. Therefor report_file
                        # will always be set. The generate_pdf call here is only needed in case
                        # the code is changed to clear report_request.pdf_file column when the
                        # data in this table gets too big (currently whole table rows are deleted)
                        report_file = report.generate_pdf(add_watermark=False)

app/templates/chat2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat Room</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.8/socket.io.min.js"></script>
</head>
<body>
    <script type="text/javascript">
        $(document).ready(function(){
            var sock = io.connect('http://127.0.0.1:5000');
            sock.on('connect', function(){
                var connect_string = 'new_connect';
                sock.send(connect_string);
            });

            sock.on('hello', function(msg){
                $('#messages').append('<li>' +'>>Hello :'+ msg + '</li>');
                console.log('Received Hello Message');
            });

            sock.on('message', function(msg){
                // console.log(type(msg));
                if(msg.type === 'normal'){
                    $('#messages').append('>> '+msg.message+'<br>');
                }else{
                    $('#messages').append('<li>' + msg.message + '</li>');
                }
                console.log('Received Message : '+msg.type);
            });



            $('#sendbutton').on('click', function(){
                sock.send($('#myMessage').val());
                $('#myMessage').val('');
            });
        });


    </script>
    <ul id="messages"></ul>
    <input type="text" id="myMessage">
    <button id="sendbutton">Send</button>

</body>
</html>

app/templates/head.html
<p>{{data.printer}}</p>
<button type="submit">print</button>

{% block content %}{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    />

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"
    />

    <!-- 부가적인 테마 -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"
    />

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>

    <!-- ReportBro Desiner -->
    <link
      href="{{ url_for('static', filename='reportbro/reportbro.css',  version='3.2.0') }}"
      rel="stylesheet"
      type="text/css"
    />
    <script src="{{ url_for('static', filename='reportbro/reportbro.js',  version='3.2.0') }}"></script>
    <script src="{{ url_for('static', filename='js/axios.min.js', version='1.0.0') }}"></script>
    <script src="{{ url_for('static', filename='js/knockout-3.5.1.min.js') }}"></script>

    <link
      href="{{ url_for('static', filename='css/styles.css',  version='1.0.0') }}"
      rel="stylesheet"
      type="text/css"
    />
  </head>
  <body>
    <div class="container">
      {% include "nav.html" %} {% include "vol_cur_view.html" %}

      <form action="/search" method="post">
        <input type="date" name="startTime" />
        <input type="date" name="endTime" />
        <button type="submit">찾기</button>
      </form>

      <form action="/print" method="post">{% include "head.html" %}</form>
    </div>
  </body>
</html>

app/templates/layout.back.html
<!DOCTYPE html>
<html>
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    />

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"
    />

    <!-- 부가적인 테마 -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"
    />

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>

    <!-- ReportBro Desiner -->
    <link
      href="{{ url_for('static', filename='reportbro/reportbro.css',  version='3.2.0') }}"
      rel="stylesheet"
      type="text/css"
    />
    <script src="{{ url_for('static', filename='reportbro/reportbro.js',  version='3.2.0') }}"></script>
    <script src="{{ url_for('static', filename='js/axios.min.js', version='1.0.0') }}"></script>
    <script src="{{ url_for('static', filename='js/knockout-3.5.1.min.js') }}"></script>

    <link
      href="{{ url_for('static', filename='css/styles.css',  version='1.0.0') }}"
      rel="stylesheet"
      type="text/css"
    />
  </head>
  <body>
    <div class="container">
      {% include "nav.html" %}
      <div id="content">{% block content %}{% endblock %}</div>
    </div>
  </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    />
    <meta charset="utf-8" />
    <title>LED 상태 조회 리포팅 페이지</title>

    <link
      href="{{ url_for('static', filename='reportbro/reportbro.css',  version='3.2.0') }}"
      rel="stylesheet"
      type="text/css"
    />
    <script src="{{ url_for('static', filename='reportbro/reportbro.js',  version='3.2.0') }}"></script>
    <script src="{{ url_for('static', filename='js/axios.min.js', version='1.0.0') }}"></script>
    <script src="{{ url_for('static', filename='js/knockout-3.5.1.min.js') }}"></script>
            <!-- 합쳐지고 최소화된 최신 CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

            <!-- 부가적인 테마 -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    
            <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
    <link
      href="{{ url_for('static', filename='css/styles.css',  version='1.0.0') }}"
      rel="stylesheet"
      type="text/css"
    />


    <script type="text/javascript"></script>
  </head>

  <body>
    <div id="container">
      <header>
        <nav>
          <a href="/led/index" id="menu_album" class=""> 조회 </a>
          <a href="/report/edit" id="menu_report" class=""> 리포팅 </a>
        </nav>
      </header>

      <!-- Content Wrapper -->
      <div id="content">{% block content %}{% endblock %}</div>
      <!-- /Content Wrapper -->
    </div>
    <!-- container -->
  </body>
</html>

app/templates/nav.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button
        type="button"
        class="navbar-toggle collapsed"
        data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1"
      >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#">Link <span class="sr-only">(current)</span></a>
        </li>
        <li><a href="/view_table">조회</a></li>
        <li><a href="#">인쇄</a></li>
        <li><a href="/report">리포트</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search" />
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <li class="dropdown">
          <a
            href="#"
            class="dropdown-toggle"
            data-toggle="dropdown"
            role="button"
            aria-expanded="false"
            >Dropdown <span class="caret"></span
          ></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/templates/print.html
<h1>{{data}}</h1>

app/templates/report.html
{% extends 'layout.html' %} {% block content %}
<div id="reportbro"></div>
<script type="text/javascript">

  function saveReport() {
      const report = rb.getReport();

      // console.log(JSON.stringify(report));
      axios.put('{{ url_for('report.save', report_type='led_report') }}', {
          report: report
        }).then(function (response) {
              // report definition saved successfully,
              // set modified flag to false to disable save button
              rb.setModified(false);
          })
          .catch(function (error) {
              alert('saving report failed');
          })
  }

  const report = {{ report_definition|safe }};
  const rb = new ReportBro(document.getElementById('reportbro'), {
      reportServerUrl: "{{ url_for('report.run') }}",
      saveCallback: saveReport,
  });
  if (report) {
      rb.load(report);
  }
</script>
{% endblock %}

app/templates/template.html
<div>
    {% for i in list %}

    <span>{{i[0]}}</span><span>{{i[1]}}</span><span>{{i[2]}}</span><br>
    {% endfor %}
</div>

app/templates/view_print.html
<p>{{data.printer}}</p>
<button type="submit">print</button>

{% block content %}{% endblock %}

app/templates/view_table.html
{% block content %}
<table class="table">
    {% for i in data.list %}
    <tr>
    <td>{{i[0]}}</td><td>{{i[1]}}</td><td>{{i[2]}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/vol_cur_view.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>

<!--<div class="row">
  <div class="col-md-2">
    <h3>전원상태:</h2>
  </div>
  <div class="col-md-2">
    <h3 class="pwst">꺼짐</h2>
  </div>
</div>
-->
<div class="row">
  <div class="col-md-2">
    <h3>현재전압:</h2>
  </div>
  <div class="col-md-2">
    <h3 class="vol">0</h2>
  </div>
  <div class="col-md-2">
    <h3>현재전류:</h2>
  </div>
  <div class="col-md-2">
    <h3 class="cur">0</h2>
  </div>
  <div class="col-md-2">
    <h3>사용전력:</h2>
  </div>
  <div class="col-md-2">
    <h3 class="pow">0</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="chart-container">
      <canvas id="vChart" width="100%" height="70"></canvas>
    </div>
  </div>
  <div class="col-md-4">
    <div class="chart-container">
      <canvas id="iChart" width="100%" height="70"></canvas>
    </div>
  </div>
  <div class="col-md-4">
    <div class="chart-container">
      <canvas id="pChart" width="100%" height="70"></canvas>
    </div>
  </div>
</div>

<script type="text/javascript">
    const ctx = document.getElementById("vChart").getContext("2d");
    const ctx1 = document.getElementById("iChart").getContext("2d");
    const ctx2 = document.getElementById("pChart").getContext("2d");

    const MAX_DATA_COUNT = 10;

    var socket = io.connect();
    var vdata = []
    var idata = []
    var pdata = []

    const vChart = new Chart(ctx,{
      type: "line",
        data: {
          datasets: [{ label: "Volt",  }],
        },
        options: {
          borderWidth: 3,
          borderColor: ['rgba(255, 99, 132, 1)',],
        },
    })

    const iChart = new Chart(ctx1,{
      type: "line",
        data: {
          datasets: [{ label: "amp",  }],
        },
        options: {
          borderWidth: 3,
          borderColor: ['rgba(99, 255, 132, 1)',],
        },
    })

    const pChart = new Chart(ctx2,{
      type: "line",
        data: {
          datasets: [{ label: "watts",  }],
        },
        options: {
          borderWidth: 3,
          borderColor: ['rgba(99, 99, 255, 1)',],
        },
    })

    function addData(chart,label, data){
      chart.data.labels.push(label);
      chart.data.datasets.forEach((dataset) => {
        dataset.data.push(data)
      })
      chart.update();
    }

    function removeFirstData(chart) {
      chart.data.labels.splice(0, 1);
      chart.data.datasets.forEach((dataset) => {
        dataset.data.shift();
      });
    }

    socket.on( 'connect', function() {
      socket.emit( 'my event', {
        data: 'User Connected'
      } )
    } )

    socket.on( 'updateSensorData', function( msg ) {

        data = JSON.parse(msg.value)
        console.log(data)
        $('h3.vol').text(data.U + 'V')
        $('h3.cur').text(data.I + 'A')
        $('h3.pow').text(data.P + 'W')

        var today = new Date();   
        var minutes = ('0' + today.getMinutes()).slice(-2);
        var seconds = ('0' + today.getSeconds()).slice(-2); 
        var timeString = minutes  + ':' + seconds;

        if (vChart.data.labels.length > MAX_DATA_COUNT) {
          removeFirstData(vChart);
          removeFirstData(iChart);
          removeFirstData(pChart);
        }
        addData(vChart,timeString, data.U);
        addData(iChart,timeString, data.I);
        addData(pChart,timeString, data.P);

    })
  </script>